[build]
  command = "npm run build:prod"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=604800"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=604800"

[[headers]]
  for = "/assets/pwa/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/events"
  to = "/events/"
  status = 301

[[redirects]]
  from = "/events/index.html"
  to = "/events/"
  status = 301

[[redirects]]
  from = "/register/:eventId"
  to = "https://cyp-admin.netlify.app/register/:eventId"
  status = 302

[[redirects]]
  from = "/contact-us"
  to = "/contact"
  status = 301
